# Generated by Django 4.2 on 2024-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('instamojo_response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
