# Generated by Django 5.1.5 on 2025-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_rekhi_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
