# Generated by Django 5.1.5 on 2025-06-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astrobooking',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='astrobooking',
            name='last_name',
        ),
    ]
