# Generated by Django 5.1.5 on 2025-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_first_name_astrobooking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrobooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
